// よく食べる食事リスト。kcal は目安値。
// 食べ物の名前を入力すると候補が出て、kcal が自動入力される。
const FOOD_DATABASE = [
  // 主食
  { name: "ご飯（普通盛り）",   kcal: 270 },
  { name: "ご飯（小盛り）",     kcal: 180 },
  { name: "ご飯（大盛り）",     kcal: 360 },
  { name: "おにぎり（1個）",    kcal: 180 },
  { name: "食パン（1枚）",      kcal: 160 },
  { name: "うどん（かけ）",     kcal: 280 },
  { name: "そば（ざる）",       kcal: 290 },
  { name: "ラーメン",           kcal: 500 },
  { name: "パスタ",             kcal: 420 },
  { name: "チャーハン",         kcal: 600 },
  // タンパク質・おかず
  { name: "卵（1個）",          kcal: 80  },
  { name: "卵焼き",             kcal: 120 },
  { name: "豆腐（半丁）",       kcal: 70  },
  { name: "鶏むね肉（100g）",   kcal: 110 },
  { name: "鶏もも肉（100g）",   kcal: 200 },
  { name: "鮭の塩焼き",         kcal: 170 },
  { name: "唐揚げ（2〜3個）",   kcal: 250 },
  { name: "サラダチキン",       kcal: 110 },
  { name: "ツナ缶（1缶）",      kcal: 60  },
  { name: "納豆（1パック）",    kcal: 100 },
  // 野菜・汁物
  { name: "サラダ（小）",       kcal: 30  },
  { name: "サラダ（大）",       kcal: 60  },
  { name: "味噌汁",             kcal: 40  },
  { name: "野菜炒め",           kcal: 150 },
  { name: "ほうれん草おひたし", kcal: 30  },
  // 果物・デザート
  { name: "バナナ（1本）",      kcal: 90  },
  { name: "りんご（半個）",     kcal: 65  },
  { name: "みかん（1個）",      kcal: 45  },
  { name: "ヨーグルト（100g）", kcal: 100 },
  { name: "無糖ヨーグルト",     kcal: 65  },
  { name: "アイスクリーム",     kcal: 200 },
  { name: "チョコレート（1片）",kcal: 130 },
  { name: "プリン",             kcal: 150 },
  // 飲み物
  { name: "牛乳（200ml）",      kcal: 130 },
  { name: "豆乳（200ml）",      kcal: 100 },
  { name: "コーラ（500ml）",    kcal: 225 },
  { name: "オレンジジュース",   kcal: 84  },
  { name: "ラテ・カフェオレ",   kcal: 120 },
  // 外食・コンビニ
  { name: "牛丼（並）",         kcal: 650 },
  { name: "カレーライス",       kcal: 850 },
  { name: "ハンバーガー",       kcal: 400 },
  { name: "コンビニサンドイッチ",kcal: 300 },
  { name: "コンビニ弁当",       kcal: 700 },
  { name: "焼き肉定食",         kcal: 800 },
  // 間食
  { name: "ポテトチップス（小袋）",kcal: 130 },
  { name: "おせんべい（2枚）",  kcal: 80  },
  { name: "クッキー（2枚）",    kcal: 100 },
  { name: "プロテインバー",     kcal: 200 },
  { name: "プロテイン（1杯）",  kcal: 120 },
];
